### ISSUE TITLE
English Styling

### ISSUE THREAD

**Issue by VScacchitti** [VScacchitti/HomeworkHelper#30]
Just a heads up we need to change the way we style the HTML of the English page. If we can change the textarea and make in input field that takes text it would be greatly appreciated.  It just makes using the APIs work much more smoothly.

![Screen Shot 2020-09-17 at 8 21 20 PM](https://user-images.githubusercontent.com/67161794/93541008-5c8ae700-f923-11ea-8378-752c1a011a91.png)

I included the above image as a reference. the grammar input can be styled to look like a textarea. 

We would also need a place to return the definition for the dictionary., this can be a larger box that we can also return the grammar information to.  

You both rock!

**Comment by rebecca88oliver** [comment]
Mostly done, still needs box for grammar return and dictionary return sometimes goes out of it's bounds.

**Comment by VScacchitti** [comment]
All set!
